# Generated by Django 3.2 on 2021-05-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contact', '0002_address_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[('private', 'Privat'), ('business', 'Business')], default='private', max_length=20),
        ),
    ]
